defaults:
  build: ALLOW
  block-break: INHERIT
  block-place: INHERIT
  pvp: INHERIT
  damage: ALLOW
  fall-damage: INHERIT
  hunger: ALLOW
  item-drop: ALLOW
  item-pickup: ALLOW
  explosions: ALLOW
  fire-spread: ALLOW
  mob-spawn: ALLOW
  projectiles: ALLOW
  vehicle-use: ALLOW
  interact: ALLOW

messages:
  denied: "&cNon puoi farlo in questa zona."
