package it.legacynetwork.chickenwars.persistence;

import static org.junit.jupiter.api.Assertions.*;
import it.legacynetwork.chickenwars.mode.MatchMode;
import it.legacynetwork.chickenwars.routing.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.Executor;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class JdbcPersistenceTest {
    private JdbcDataSource dataSource;
    private final Executor direct=Runnable::run;
    @BeforeEach void migrate() throws Exception {dataSource=new JdbcDataSource();dataSource.setURL("jdbc:h2:mem:"+UUID.randomUUID()+";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");MigrationRunner runner=new MigrationRunner(dataSource,getClass().getClassLoader());runner.migrate();runner.migrate();}
    @Test void migrationIsOrderedAndIdempotent() throws Exception {try(Connection c=dataSource.getConnection();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT COUNT(*) FROM cw_schema_history")){assertTrue(r.next());assertEquals(1,r.getInt(1));}}
    @Test void progressionAndStatisticsRoundTrip(){UUID id=UUID.randomUUID();JdbcProgressionRepository p=new JdbcProgressionRepository(dataSource,direct);PlayerProgressRecord expected=new PlayerProgressRecord(id,123,45,10);p.save(expected).toCompletableFuture().join();assertEquals(123,p.load(id).toCompletableFuture().join().getTotalExperience());JdbcStatisticsRepository stats=new JdbcStatisticsRepository(dataSource,direct);stats.save(new it.legacynetwork.chickenwars.statistics.ModeStatistics(id,MatchMode.SOLO,2,1,3,4,2,1,2,60,9)).toCompletableFuture().join();assertEquals(2,stats.load(id).toCompletableFuture().join().get(0).getEliminations());}
    @Test void quickBuySlotsAndSelectionPersist(){UUID id=UUID.randomUUID();JdbcQuickBuyRepository repo=new JdbcQuickBuyRepository(dataSource,direct);Map<Integer,String> slots=new LinkedHashMap<Integer,String>();slots.put(10,"wool");repo.savePreset(new QuickBuyPresetRecord(id,"one","One",true,slots)).toCompletableFuture().join();repo.savePreset(new QuickBuyPresetRecord(id,"two","Two",false,Collections.<Integer,String>emptyMap())).toCompletableFuture().join();repo.selectPreset(id,"two").toCompletableFuture().join();assertEquals(2,repo.loadPresets(id).toCompletableFuture().join().size());assertTrue(repo.loadPresets(id).toCompletableFuture().join().get(1).isSelected());}
    @Test void jdbcLedgerIsIdempotentAndTransactional(){UUID id=UUID.randomUUID();JdbcCoinTransactionRepository repo=new JdbcCoinTransactionRepository(dataSource,direct);repo.credit(id,20,"c").toCompletableFuture().join();repo.credit(id,20,"c").toCompletableFuture().join();repo.debit(id,5,"d").toCompletableFuture().join();assertEquals(15,repo.balance(id).toCompletableFuture().join());assertEquals(2,repo.history(id).toCompletableFuture().join().size());}
    @Test void jdbcMatchFinalizationIsIdempotent(){UUID id=UUID.randomUUID();JdbcMatchPersistence store=new JdbcMatchPersistence(dataSource,direct);MatchFinalizationRequest request=new MatchFinalizationRequest("match",MatchMode.SOLO,"red",Collections.singletonList(new MatchParticipantRecord(id,"red",true,10,2,1,1,0,1,3,20)),100);assertTrue(store.finalizeMatch(request).toCompletableFuture().join().isApplied());assertFalse(store.finalizeMatch(request).toCompletableFuture().join().isApplied());assertEquals(2,new JdbcProgressionRepository(dataSource,direct).load(id).toCompletableFuture().join().getCoins());assertEquals(1,new JdbcCoinTransactionRepository(dataSource,direct).history(id).toCompletableFuture().join().size());}
    @Test void jdbcRoutingReservesClaimsAndExpires(){JdbcInstancePublisher publisher=new JdbcInstancePublisher(dataSource,direct);publisher.heartbeat(new GameInstanceDescriptor("i","game-1",MatchMode.SOLO,"a",InstanceStatus.WAITING,0,8,100,true)).toCompletableFuture().join();JdbcRoutingCoordinator routing=new JdbcRoutingCoordinator(dataSource,direct,50,10);UUID player=UUID.randomUUID();RouteResult route=routing.route(player,MatchMode.SOLO,null,"request",110).toCompletableFuture().join();assertTrue(route.isSuccessful());String reservation=route.getReservations().get(0).getReservationId();assertTrue(routing.claim(reservation,player,111).toCompletableFuture().join());assertFalse(routing.claim(reservation,player,111).toCompletableFuture().join());RouteResult expires=routing.route(UUID.randomUUID(),MatchMode.SOLO,null,"expire",120).toCompletableFuture().join();assertEquals(1,routing.cleanup(131).toCompletableFuture().join());assertFalse(routing.claim(expires.getReservations().get(0).getReservationId(),expires.getReservations().get(0).getPlayerId(),131).toCompletableFuture().join());}
    @Test void expiredIdempotencyKeyReturnsStableFailure(){JdbcInstancePublisher publisher=new JdbcInstancePublisher(dataSource,direct);publisher.heartbeat(new GameInstanceDescriptor("i","game-1",MatchMode.SOLO,"a",InstanceStatus.WAITING,0,8,100,true)).toCompletableFuture().join();JdbcRoutingCoordinator routing=new JdbcRoutingCoordinator(dataSource,direct,50,5);UUID id=UUID.randomUUID();assertTrue(routing.route(id,MatchMode.SOLO,null,"same",100).toCompletableFuture().join().isSuccessful());routing.cleanup(106).toCompletableFuture().join();assertEquals(RouteFailure.STALE_INSTANCE,routing.route(id,MatchMode.SOLO,null,"same",106).toCompletableFuture().join().getFailure());}
    @Test void distributedReconnectPrefersPreviousInstanceOnce(){JdbcInstancePublisher publisher=new JdbcInstancePublisher(dataSource,direct);publisher.heartbeat(new GameInstanceDescriptor("old","game-old",MatchMode.SOLO,"a",InstanceStatus.INGAME,8,8,100,false)).toCompletableFuture().join();JdbcReconnectCoordinator reconnect=new JdbcReconnectCoordinator(dataSource,direct,50,10);UUID id=UUID.randomUUID();reconnect.remember(id,"old",200).toCompletableFuture().join();RouteResult result=reconnect.reconnect(id,"rejoin",110).toCompletableFuture().join();assertTrue(result.isSuccessful());assertEquals("old",result.getInstance().getInstanceId());assertFalse(reconnect.reconnect(id,"again",110).toCompletableFuture().join().isSuccessful());}
}
