server:
  id: "lobby-01"

language:
  fallback: "en"
  channel: "NetworkLang"

scoreboard:
  config-file: "scoreboard.yml"

bossbar:
  config-file: "bossbar.yml"

messages:
  italian-file: "messages_it.yml"
  english-file: "messages_en.yml"

join:
  selected-slot:
    enabled: true
    slot: 1
    delay-ticks: 2
    force: true
